[[redirects]]
    from = "/heroes/static/*.png"
    to = "/static/:splat"
    status = 301
    force = false
[[redirects]]
    from = "/heroes/*"
    to = "/heroes/:splat"
    status = 301
    force = false
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = false