/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://3miollwplfgupk55wdxm6ud6ei.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xird6roljrheneplnsg26q3ohq",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_3RZ6N8Mgs",
    "aws_user_pools_web_client_id": "5r5dot3avo9ffnek7k114hu25l",
    "oauth": {}
};


export default awsmobile;
